accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.shortcuts import render, redirect
from receipts.views import (
    ReceiptListView
)

from accounts.views import signup




urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin



urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),

]

receipts/urls.py
from django.urls import path
from django.urls import reverse_lazy
from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    AccountListView,
    ExpenseCategoryCreateView,
    AccountCreateView
)






urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path("categories/", ExpenseCategoryListView.as_view(), name="list_categories"),
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path("categories/create/", ExpenseCategoryCreateView.as_view(), name="create_category"),
    path("accounts/create/", AccountCreateView.as_view(), name="create_account"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )
    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3,)
    tax = models.DecimalField(max_digits=10, decimal_places=3,)
    date = models.DateTimeField(null=True)
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return self.vendor

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
            "form": form
        }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from receipts.models import Account, Receipt, ExpenseCategory
from django.views.generic.base import RedirectView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
user = User.objects.create_user


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"
    success_url = reverse_lazy("home")

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]


    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/expense_list.html"


    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/accounts_list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/category_create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()

        return redirect("list_categories")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/create_account.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()

        return redirect("account_list")

receipts/templates/receipts/accounts_list.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Receipts</title>
</head>

<body>
  <main>
    <div>
        <li>
          <a href="{% url 'create_account' %}">Create an Account </a>
        </li>
    </div>
    <h1>Accounts</h1>
    <div>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Number</th>
          <th>Number of receipts</th>
        </tr>
      </thead>
      <tbody>
        {% for account in receipt_list %}
        <tr>
        <td>{{account.account}}</td>
        <td>{{account.account.number}}</td>
        <td>{{account.receipt.all|length}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
  </main>


</body>

</html>

receipts/templates/receipts/category_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Create Category</title>
</head>

<body>
    <main>
        <div>
            <h1>Create Cateogory</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="control">
                    <button class="button">Create</button>
                </div>
            </form>
        </div>
    </main>

</body>

</html>

receipts/templates/receipts/create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Document</title>
</head>
<body>
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="control">
                    <button class="button">Create</button>
                </div>
            </form>
        </div>
    </main>

</body>

</html>

receipts/templates/receipts/create_account.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Create Account</title>
</head>

<body>
    <main>
        <div>
            <h1>Create Account</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="control">
                    <button class="button">Create</button>
                </div>
            </form>
        </div>
    </main>

</body>

</html>

receipts/templates/receipts/expense_list.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Receipts</title>
</head>

<body>
  <main>
    <div>
    <nav>
      <ul>
        <li>
          <a href="{% url 'create_category' %}">Create Category</a>
        </li>
    <h1>Expense by Category</h1>
    <table>
      <thead>
        <tr>
          <th>Expense Category</th>
          <th>Number of Receipts</th>
        </tr>
      </thead>
      <tbody>
        {% for category in expensecategory_list %}
        <tr>
        <td>{{category.name}}</td>
        <td>{{category.receipts.all|length}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  </main>


</body>

</html>

receipts/templates/receipts/list.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Receipts</title>
</head>
<body>
  <nav>
    <ul>
      <li>
        <a href="{% url 'logout' %}">Logout</a>
      </li>
      <li>
        <a href="{% url 'signup' %}">sign up</a>
      </li>
      <li>
        <a href="{% url 'login' %}">Login</a>
      </li>
      <li>
        <a href="{% url 'create_receipt' %}">Create a Receipt</a>
      </li>
      <li>
        <a href="{% url 'create_category' %}">Create Category</a>
      </li>
      <li>
        <a href="{% url 'create_account' %}">Create Account</a>
      </li>
      <li>
        <a href="{% url 'account_list' %}">Account List</a>
      </li>
      <li>
        <a href="{% url 'list_categories' %}">Category List</a>
      </li>
  <main>
    <div>
      <h1>My Receipts</h1>
        <table>
          <thead>
            <tr>
              <th>Vendor</th>
              <th>Total</th>
              <th>Tax</th>
              <th>Date</th>
              <th>Category</th>
              <th>Account</th>
            </tr>
          </thead>
      <tbody>
        {% for item in receipt_list %}
        <tr>
          <td>{{item.vendor}}</td>
          <td>{{item.total}}</td>
          <td>{{item.tax}}</td>
          <td>{{item.date|date:"m-d-Y" }}</td>
          <td>{{item.category}}</td>
          <td>{{item.account}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
  </main>


</body>

</html>